# Generated by Django 5.0.4 on 2024-04-19 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('especie', models.CharField(choices=[('d', 'Perro'), ('c', 'Gato'), ('h', 'Hamster'), ('p', 'Perico')], max_length=30)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('m', 'Macho'), ('h', 'Hembra')], max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
